### PR TITLE
Create .pullapprove.yml

### PR DESCRIPTION
**Pull request by can-z**
Use :+1: and :-1: to approve or reject a PR; PRs without a :+1: cannot be merged.

### CODE REVIEW

**Comment by can-z** [comment]
👍

**Comment by can-z** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/can-z/kudos-server/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=can-z/kudos-server)

**Comment by can-z** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;z4fsTUvI&#x2F;11-add-pullapprove"> Add pullapprove</a>

**Comment by xwu30** [comment]
👍

**Pull request merged**
