### PR TITLE
Add integration test example

### PR DESCRIPTION
**Pull request by can-z**
- Add a test for integration tests (i.e. tests that spin up a server and make HTTP requests to it)
- Clean up the dependencies a bit
- Switch from nose to pytest
- Add Gemnasium and TravisCI badges.

### CODE REVIEW

**Comment by can-z** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;DNgTZ2Cn&#x2F;10-add-example-integration-test"> Add example integration test</a>

**Comment by can-z** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fvmRtLkK&#x2F;9-add-gymnasium"> Add gymnasium</a>

**Comment by can-z** [comment]
👍 before merging the pullapprove PR

**Comment by can-z** [comment]
I mean Approved

**Comment by can-z** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/can-z/kudos-server/pull-request/4/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=can-z/kudos-server)

**Comment by can-z** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;re9BQBUh&#x2F;13-set-up-local-python-3-testing"> Set up local python 3 testing</a>

**Comment by xwu30** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/can-z/kudos-server/pull-request/4/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=can-z/kudos-server)

**Comment by xwu30** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/can-z/kudos-server/pull-request/4/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=can-z/kudos-server)

**Pull request merged**
